name: Dump and Commit Alliance Wiki Pages

on:
  # Manual run
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 5"

permissions:
  contents: write  # needed to push back to the repo

jobs:
  dump-and-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Use GITHUB_TOKEN so we can push back
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # use requirements.txt if you add more libs later; for now just requests
          pip install requests

      - name: Run wiki dump
        run: |
          python dump_wiki_pages.py
        env:
          # (Optional) make API endpoint configurable later if you want
          # API_ENDPOINT: https://docs.alliancecan.ca/mediawiki/api.php
          PYTHONUTF8: "1"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit changes (if any)
        run: |
          # Only stage the wiki_pages folder to avoid committing unrelated files
          git add -A wiki_pages

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # Nice, minimal commit message with timestamp
          ts="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git commit -m "Update wiki_pages dump ($ts)"
          git push origin HEAD:${{ github.ref_name }}
