name: Dump and Commit Alliance Events

on:
  # Manual run
  workflow_dispatch: {}
  # Daily at 07:00 UTC
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write

jobs:
  dump-and-commit:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run events page dump
        run: python dump_events_page.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Commit changes (if any)
        run: |
          git add -A wiki_pages

          if git diff --staged --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          ts="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          git commit -m "Update events dump ($ts)"
          git push origin HEAD:${{ github.ref_name }}
